swagger: "2.0"
info:
  title: transaction api
  version: "1.0"
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /accounts/create:
    post:
      description: Create a new account with some initial amount
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              token:
                description: idempotency token
                type: string
                example: "101"
              initial_amount:
                description: a decimal number converted to string
                type: string
                example: "12345.78"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                description: created account id
                example: "A10001"
  /account/info:
    post:
      description: Retrieve current amount on account
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              id:
                description: account id
                type: string
                example: "A10001"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              amount:
                type: string
                description: a decimal number converted to string
                example: "12345.78"
  /transactions/create:
    post:
      description: Create a new transaction between accounts
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              token:
                description: idempotency token
                type: string
                example: "102"
              src_account_id:
                description: source account id
                type: string
                example: "A10001"
              dst_account_id:
                description: destination account id
                type: string
                example: "A10002"
              amount:
                description: amount to transfer from src_account_id to dst_account_id
                type: string
                example: "1070.00"
      responses:
        200:
          description: OK
