swagger: "2.0"
info:
  title: transaction api
  version: "1.0"
basePath: /v1
consumes:
  - text/plain; charset=utf-8
produces:
  - text/plain; charset=utf-8
paths:
  /sessions/create:
    post:
      description: Create a new client session
      responses:
        200:
          description: OK, created session id
          schema:
            type: string
            description: created session id
            example: "S10001"
  /accounts/create:
    post:
      description: Create a new account with some initial amount
      parameters:
        - in: query
          name: token
          description: idempotency token, e.g. '123'
          type: string
        - in: query
          name: amount
          description: for example '174724.54'
          type: string
      responses:
        200:
          description: OK, created account id
          schema:
            type: string
            description: created account id
            example: "A10001"
        400:
          description: error in parameters
  /account/amount:
    post:
      description: Retrieve current amount on account
      parameters:
        - in: query
          name: account_id
          description: account id, e.g. 'A10001'
          type: string
      responses:
        200:
          description: OK, amount on account
          schema:
            type: string
            description: a decimal number converted to string
            example: "12345.78"
        400:
          description: error in parameters
  /transactions/create:
    post:
      description: Create a new transaction between accounts
      parameters:
        - in: query
          name: token
          description: idempotency token, e.g. '102'
          type: string
        - in: query
          name: src_account_id
          description: source account id, e.g. 'A10001'
          type: string
        - in: query
          name: dst_account_id
          description: destination account id, e.g. 'A10002'
          type: string
        - in: query
          name: amount
          description: amount to transfer from src_account_id to dst_account_id, e.g. '1070.00'
          type: string
      responses:
        200:
          description: OK, created transaction id
          schema:
            type: string
            description: created transaction id
            example: "T10001"
        400:
          description: error in parameters
